### ISSUE TITLE
Loop stopped in the first for loop

### ISSUE THREAD

**Issue by zedavid** [FurhatRobotics/camerafeed-demo#1]
Hi! I followed the steps in the README file, but when I run the python script, the print message after the for loop inside the while loop never appears. Do you have any idea why this is happening?

Thanks!

**Comment by SquaredCanine** [comment]
Hi!

It could be that the print message is not executed because data is never received, ergo the function waits until data is received. This could be because the IP is not setup properly, the socket is not connecting (maybe firewall?), or the robot is not of type 'Research'. For more information on robot type please visit [our docs](https://docs.furhat.io/robot/#robot-type)

**Comment by lafredi** [comment]
Hi,

I have exactly the same problem,  the print message after the for loop inside the while loop never appears.
because the data is never received.
the IP is well configured, and I guess the robot is type 'Research'

do you have an idea of the source of the problem plz ?

**Comment by SquaredCanine** [comment]
"guess the robot is type 'Research", do you have the `Camera` tab in the settings of the robot? @lafredi

**Comment by SquaredCanine** [comment]
Also make sure the skill is started before the python script. And the laptop + robot are on the same network and are able to communicat with each other.
